sudo: false
language: go

env:
    - GO111MODULE=on

go:
    - 1.9.x
    - 1.10.x
    - 1.11.x

before_install:
    - go get github.com/mattn/goveralls

script:
    - go test -covermode=count -coverprofile=profile.cov
    - $GOPATH/bin/goveralls -coverprofile=profile.cov -service=travis-ci
    - go build -o main
